kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "simple-pipeline" 
spec:
  source:
    contextDir: simple-pipeline 
    git:
      uri: "https://github.com/ilyxaxxx/DO288-apps" 
      ref: "simple-pipeline"
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy: 
      jenkinsfilePath: Jenkinsfile